.PHONY: all

all: SDLTest.exe boids

# if it says emcc doesn't exist, run emsdk_env before make to fix it
# to fix it permanently, run emsdk activate --permanent
EMCC := emcc
CC := D:/mingw-w64/x86_64-8.1.0-win32-seh-rt_v6-rev0/mingw64/bin/g++.exe # FIXME 
FLAGS := -std=c++17 -Wall -Wextra -Wpedantic -g 

SDLTest.exe: *.cc
	$(CC) $(FLAGS) *.cc -o SDLTest.exe -ISDL2/include -LSDL2/lib -lmingw32 -lSDL2main -lSDL2

boids: boids.js boids.html boids.wasm
boids.js boids.html boids.wasm: *.cc
	$(EMCC) main.cc -sWASM=1 -sUSE_SDL=2 -sUSE_SDL_IMAGE=2 -O3 -o boids.js -o boids.html